spring.application.name=btg-backend

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duvanfercho0511@gmail.com
spring.mail.password=xkbu mvqj oxuu fovu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.servlet.context-path=/api


spring.mongodb.uri=mongodb+srv://duvan:jYmUTlLmTNQIZZOi@cluster0.f2xs1c8.mongodb.net/btg?retryWrites=true&w=majority